---

    name: "Code Review"
    
    on: [pull_request]
    
    jobs:
    
      danger:
        name: 'Workflow Rules'
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout Code'
            uses: actions/checkout@v3
    
          - name: 'Check Danger Rules'
            uses: danger/danger-js@11.2.6
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      phpcs:
        name: 'PHP CS'
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout Code'
            uses: actions/checkout@v3
    
          - name: 'Setup PHP'
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.1'
              tools: 'phpcs'
              coverage: none
    
          - name: 'Run Check'
            run: composer run phpcs
    
      theme:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v2
    
          - name: 'Setup Node'
            uses: actions/setup-node@v3
            with:
              node-version: 16
    
          - name: 'Install Packages'
            run: npm ci --include=dev
    
          - name: 'Lint JS'
            run: npm run lint:js